name: Publish Python SDK

on:
  push:
    tags:
      - 'python-v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd python-sdk
          python -m pip install --upgrade pip
          pip install build twine

      - name: Run tests
        run: |
          cd python-sdk
          pip install -e ".[dev]"
          pytest

      - name: Build package
        run: |
          cd python-sdk
          python -m build

      - name: Publish to Test PyPI
        if: github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          cd python-sdk
          python -m twine upload --repository testpypi dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd python-sdk
          python -m twine upload dist/*
