# Spectral OpenAPI Linting Configuration
# https://docs.stoplight.io/docs/spectral/

extends:
  - "spectral:oas"

rules:
  # Enforce operation IDs are unique
  operation-operationId-unique: true

  # Path parameters should be defined in operation
  path-params: warn  # Downgrade to warning since we have 18 missing params

  # Contact should have name, url, and email
  contact-properties: warn  # We have name and url, email is optional for internal APIs

  # Allow operations without descriptions for now (we have minimal specs)
  operation-description: off

  # Allow missing request bodies for GET/DELETE
  operation-success-response: warn
