version: '3.8'

services:
  # Swagger UI - Interactive API Documentation
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: riptide-swagger-ui
    ports:
      - "8081:8080"
    environment:
      # Use local OpenAPI spec file
      SWAGGER_JSON: /openapi.yaml
      # Optional: Set base URL for API calls
      API_URL: http://localhost:8080
    volumes:
      # Mount OpenAPI specification
      - ./docs/api/openapi.yaml:/openapi.yaml:ro
    networks:
      - riptide-network
    restart: unless-stopped

  # RipTide API (optional - if you want to run API alongside docs)
  # Uncomment to run API with Swagger UI
  # riptide-api:
  #   build: .
  #   container_name: riptide-api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #     - WASM_PATH=/app/wasm/riptide.wasm
  #   volumes:
  #     - ./docs/api:/app/docs/api:ro
  #   networks:
  #     - riptide-network
  #   restart: unless-stopped

  # ReDoc - Alternative API Documentation (cleaner, read-only)
  redoc:
    image: redocly/redoc:latest
    container_name: riptide-redoc
    ports:
      - "8082:80"
    environment:
      SPEC_URL: /openapi.yaml
    volumes:
      - ./docs/api/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    networks:
      - riptide-network
    restart: unless-stopped

networks:
  riptide-network:
    driver: bridge

# Usage:
# 1. Start Swagger UI: docker-compose -f docker-compose.swagger.yml up -d swagger-ui
# 2. Access at: http://localhost:8081
#
# 3. Start ReDoc: docker-compose -f docker-compose.swagger.yml up -d redoc
# 4. Access at: http://localhost:8082
#
# 5. Start both: docker-compose -f docker-compose.swagger.yml up -d
#
# 6. Stop all: docker-compose -f docker-compose.swagger.yml down
