#!/bin/bash

echo "🚀 RipTide Development Commands"
echo "=============================="
echo ""
echo "Quick Commands:"
echo "  make build         - Fast incremental build"
echo "  make test          - Run tests in parallel"
echo "  make check         - Run quality checks"
echo "  make clean         - Clean artifacts & ports"
echo "  make all           - Build, test & check"
echo ""
echo "Test Commands:"
echo "  ./scripts/test-minimal.sh  - Quick smoke test (10s)"
echo "  ./scripts/quick-test.sh    - Unit tests only (30s)"
echo "  ./scripts/fast-test.sh     - Full test suite (45s)"
echo ""
echo "Development:"
echo "  ./scripts/dev-setup.sh     - Setup environment"
echo "  ./scripts/quick-build.sh   - Fast build"
echo "  ./scripts/quality-check.sh - Lints & formatting"
echo ""
echo "Port Cleanup:"
echo "  pkill -f cargo             - Kill cargo processes"
echo "  lsof -ti:8080 | xargs kill - Free port 8080"
echo ""
echo "💡 Tip: Ports are auto-freed before each build/test"