[package]
name = "riptide-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
lol_html = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
uuid = { workspace = true }
pdfium-render = { workspace = true, optional = true }

[features]
default = []
pdf = ["pdfium-render"]