[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
walkdir = "2"
regex = "1"
rayon = "1"
once_cell = "1"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
