version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - headless
    environment:
      - RUST_LOG=info
      - REDIS_URL=redis://redis:6379/0
      - HEADLESS_URL=http://headless:9123
      - SERPER_API_KEY=${SERPER_API_KEY}
    volumes:
      - artifacts-data:/data/artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  headless:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.headless
    ports:
      - "9123:9123"
    environment:
      - RUST_LOG=info
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9123/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
  artifacts-data: