---
# RipTide Metrics Configuration
# Complete metrics wiring configuration for production monitoring

# Prometheus Configuration
prometheus:
  enabled: true
  endpoint: "/metrics"
  push_gateway:
    url: "http://prometheus-pushgateway:9091"
    job_name: "riptide-api"
    enabled: false

# System Metrics Configuration
system_metrics:
  collection_interval: 30s
  enabled_metrics:
    - cpu_usage_percent
    - memory_usage_bytes
    - disk_usage_bytes
    - file_descriptor_count
    - thread_count
    - load_average
  thresholds:
    cpu_warning: 70.0
    cpu_critical: 90.0
    memory_warning: 2147483648  # 2GB
    memory_critical: 4294967296  # 4GB
    fd_warning: 8192
    fd_critical: 16384

# HTTP Request Metrics
http_metrics:
  enabled: true
  buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
  track_methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
  track_status_codes: true
  track_user_agents: false

# Phase Timing Metrics
phase_metrics:
  enabled: true
  phases:
    fetch:
      buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0]
      enabled: true
    gate:
      buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5]
      enabled: true
    wasm:
      buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0]
      enabled: true
    render:
      buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0]
      enabled: true

# Streaming Metrics Configuration
streaming_metrics:
  enabled: true
  connection_tracking: true
  message_tracking: true
  protocols:
    ndjson:
      enabled: true
      buffer_size_tracking: true
    sse:
      enabled: true
      keep_alive_tracking: true
    websocket:
      enabled: true
      ping_pong_tracking: true
  thresholds:
    error_rate_warning: 0.05
    error_rate_critical: 0.10
    drop_rate_warning: 0.10
    drop_rate_critical: 0.20

# PDF Processing Metrics
pdf_metrics:
  enabled: true
  processing_time_buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0]
  memory_tracking: true
  page_count_tracking: true
  memory_spike_detection: true
  cleanup_tracking: true
  thresholds:
    memory_spike_limit: 209715200  # 200MB
    processing_time_warning: 30.0  # 30 seconds
    processing_time_critical: 120.0  # 2 minutes

# Spider Crawling Metrics
spider_metrics:
  enabled: true
  crawl_tracking: true
  frontier_size_tracking: true
  page_rate_tracking: true
  duration_buckets: [0.1, 1.0, 5.0, 15.0, 30.0, 60.0, 300.0, 900.0, 1800.0]
  thresholds:
    pages_per_second_warning: 0.1
    frontier_size_critical: 10000

# Error Metrics Configuration
error_metrics:
  enabled: true
  error_types:
    - redis_errors
    - wasm_errors
    - http_errors
    - pdf_errors
    - spider_errors
  threshold_alerts: true
  error_rate_window: 300s  # 5 minutes

# Performance Benchmarking Configuration
benchmarking:
  enabled: true
  suites:
    - name: "http_performance"
      description: "HTTP request latency and throughput benchmarks"
      interval: 3600s  # Every hour
      metrics:
        - requests_per_second
        - p95_latency
        - p99_latency
    - name: "pdf_processing"
      description: "PDF processing performance benchmarks"
      interval: 1800s  # Every 30 minutes
      metrics:
        - processing_time_p95
        - memory_usage_peak
        - pages_per_second
    - name: "streaming_performance"
      description: "Streaming protocol performance benchmarks"
      interval: 900s  # Every 15 minutes
      metrics:
        - connection_throughput
        - message_delivery_rate
        - backpressure_events
    - name: "spider_performance"
      description: "Spider crawling performance benchmarks"
      interval: 3600s  # Every hour
      metrics:
        - crawl_rate
        - success_rate
        - frontier_efficiency

# Dashboard Configuration
dashboards:
  enabled: true
  panels:
    system_overview:
      enabled: true
      metrics:
        - cpu_usage_percent
        - memory_usage_bytes
        - active_connections
        - requests_per_second
    phase_timing:
      enabled: true
      metrics:
        - fetch_phase_duration
        - gate_phase_duration
        - wasm_phase_duration
        - render_phase_duration
    pdf_processing:
      enabled: true
      metrics:
        - pdf_processing_time
        - pdf_peak_memory_mb
        - pdf_memory_spikes_handled
    streaming_health:
      enabled: true
      metrics:
        - streaming_active_connections
        - streaming_messages_sent
        - streaming_error_rate
    spider_operations:
      enabled: true
      metrics:
        - spider_pages_crawled
        - spider_active_crawls
        - spider_pages_per_second

# SLA Configuration
sla:
  enabled: true
  objectives:
    availability:
      target: 99.9
      window: "30d"
    latency_p95:
      target: 1000  # 1 second
      window: "24h"
    latency_p99:
      target: 5000  # 5 seconds
      window: "24h"
    error_rate:
      target: 0.01  # 1%
      window: "24h"
    pdf_processing_success:
      target: 0.95  # 95%
      window: "24h"
    streaming_delivery_rate:
      target: 0.99  # 99%
      window: "1h"

# Alerting Configuration
alerting:
  enabled: true
  channels:
    - name: "ops_team"
      type: "slack"
      webhook_url: "${SLACK_WEBHOOK_URL}"
    - name: "critical_alerts"
      type: "pagerduty"
      integration_key: "${PAGERDUTY_INTEGRATION_KEY}"
  rules:
    high_error_rate:
      condition: "error_rate > 0.05"
      duration: "5m"
      severity: "warning"
      channels: ["ops_team"]
    critical_error_rate:
      condition: "error_rate > 0.10"
      duration: "1m"
      severity: "critical"
      channels: ["critical_alerts"]
    high_latency:
      condition: "p95_latency > 2000"
      duration: "10m"
      severity: "warning"
      channels: ["ops_team"]
    memory_pressure:
      condition: "memory_usage_bytes > 3221225472"  # 3GB
      duration: "5m"
      severity: "warning"
      channels: ["ops_team"]
    pdf_memory_spike:
      condition: "pdf_memory_spikes_handled > 0"
      duration: "1m"
      severity: "warning"
      channels: ["ops_team"]
    streaming_degradation:
      condition: "streaming_error_rate > 0.05"
      duration: "5m"
      severity: "warning"
      channels: ["ops_team"]

# Retention Configuration
retention:
  high_resolution: "24h"  # 1s resolution
  medium_resolution: "7d"   # 10s resolution
  low_resolution: "90d"     # 60s resolution
  cleanup_interval: "1h"

# Export Configuration
exports:
  enabled: true
  formats:
    - prometheus
    - json
    - csv
  destinations:
    - name: "s3_backup"
      type: "s3"
      bucket: "${METRICS_S3_BUCKET}"
      prefix: "metrics-backup/"
      schedule: "0 2 * * *"  # Daily at 2 AM
      enabled: false
    - name: "local_backup"
      type: "local"
      path: "/var/lib/riptide/metrics"
      schedule: "0 */6 * * *"  # Every 6 hours
      enabled: true