# RipTide Crawler Phase 0 - Resource Management Configuration
# This configuration file defines browser pooling and memory optimization settings

[browser_pool]
# Minimum number of browsers to keep in pool
min_pool_size = 2

# Maximum number of browsers in pool
max_pool_size = 5

# Initial pool size on startup
initial_pool_size = 3

# Idle timeout before browser cleanup (seconds)
idle_timeout = 30

# Maximum lifetime for a browser instance (seconds)
max_lifetime = 300

# Health check interval (seconds)
health_check_interval = 10

# Memory threshold per browser (MB)
memory_threshold_mb = 500

# Enable automatic recovery for crashed browsers
enable_recovery = true

# Maximum retries for browser operations
max_retries = 3

[memory_manager]
# Maximum total memory usage across all WASM instances (MB)
max_total_memory_mb = 2048

# Memory threshold for single instance (MB)
instance_memory_threshold_mb = 256

# Maximum number of WASM instances in pool
max_instances = 8

# Minimum number of WASM instances to keep warm
min_instances = 2

# Idle timeout for WASM instances (seconds)
instance_idle_timeout = 60

# Memory monitoring interval (seconds)
monitoring_interval = 5

# Garbage collection interval (seconds)
gc_interval = 30

# Enable aggressive memory management
aggressive_gc = false

# Memory pressure threshold (percentage)
memory_pressure_threshold = 80.0

[launcher]
# Default stealth preset ("none", "low", "medium", "high")
default_stealth_preset = "medium"

# Enable stealth mode by default
enable_stealth = true

# Page timeout for operations (seconds)
page_timeout = 30

# Enable performance monitoring
enable_monitoring = true

[performance]
# Expected performance targets
target_response_time_ms = 2000
target_success_rate_percent = 95.0
target_memory_efficiency_percent = 85.0
target_browser_utilization_percent = 70.0

# Performance monitoring settings
metrics_collection_interval = 10
performance_alert_threshold = 90.0
auto_scaling_enabled = true
auto_scaling_threshold = 80.0

[alerts]
# Memory alerts
memory_high_threshold_mb = 1600  # 80% of max_total_memory_mb
memory_critical_threshold_mb = 1840  # 90% of max_total_memory_mb

# Browser alerts
browser_crash_threshold = 3  # crashes per hour
browser_response_time_threshold_ms = 5000
browser_memory_leak_threshold_mb_per_sec = 10.0

# Instance alerts
instance_failure_threshold = 5  # failures per hour
instance_queue_threshold = 10  # pending requests

[monitoring]
# Monitoring and logging configuration
log_level = "info"
enable_metrics_export = true
metrics_export_interval = 30
enable_tracing = true
trace_sample_rate = 0.1

# Health check endpoints
health_check_enabled = true
health_check_port = 8080
health_check_path = "/health"

# Metrics endpoints
metrics_enabled = true
metrics_port = 9090
metrics_path = "/metrics"

[optimization]
# Optimization strategies
enable_instance_warmup = true
warmup_count = 2
enable_predictive_scaling = false
enable_smart_cleanup = true

# Memory optimization
enable_memory_compaction = true
compaction_interval = 120  # seconds
enable_leak_detection = true
leak_detection_sensitivity = "medium"

# Browser optimization
enable_browser_recycling = true
recycling_threshold_uses = 100
enable_resource_preloading = false
preload_common_resources = true