openapi: 3.0.0
info:
  title: RipTide API - Comprehensive Specification
  version: 1.0.0
  x-last-validated: "2025-10-10T07:44:00Z"
  description: '# RipTide Crawler API


    A high-performance web scraping and content extraction API with 59 endpoints across
    12 categories.


    ## Phase 1: Core Crawling & Event System (11 endpoints)

    - `/crawl` - Batch URL crawling with adaptive gate system

    - `/crawl/stream`, `/crawl/sse`, `/crawl/ws` - Real-time streaming

    - `/deepsearch`, `/deepsearch/stream` - Web search integration

    - `/render` - Headless browser rendering

    - `/healthz`, `/metrics` - System health and Prometheus metrics


    ## Phase 2: Advanced Extraction (14 endpoints)

    - `/strategies/*` - Multi-strategy extraction (CSS, TREK, LLM, Regex)

    - `/pdf/*` - PDF processing with progress streaming

    - `/api/v1/tables/*` - Table extraction and export (CSV/Markdown)


    ## Phase 3: Enterprise Features (34 endpoints)

    - `/spider/*` - Deep crawling with frontier management (3)

    - `/stealth/*` - Stealth configuration and testing (4)

    - `/api/v1/llm/*` - LLM provider management (4)

    - `/sessions/*` - Session and cookie management (12)

    - `/workers/*` - Async job queue and scheduling (9)

    - `/monitoring/*` - Health monitoring and alerts (6)


    ## Architecture Highlights

    - **Dual-Path Pipeline**: Fast CSS + async AI enhancement

    - **Event-Driven**: Core event bus for monitoring

    - **Circuit Breaker**: Automatic failover for dependencies

    - **Adaptive Gate**: Smart routing (raw/probes/headless/cached)


    **Total: 59 endpoints documented**

    '
  contact:
    name: RipTide API Support
    url: https://github.com/riptide/api
    email: support@riptide.dev
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: http://localhost:8080
  description: Local development
- url: https://api.riptide.example.com
  description: Production
tags:
- name: Crawling
  description: Core crawling endpoints (5)
- name: Search
  description: Deep search endpoints (2)
- name: Spider
  description: Deep crawling (3)
- name: Streaming
  description: Real-time streaming (4)
- name: Strategies
  description: Advanced extraction (2)
- name: PDF
  description: PDF processing (3)
- name: Stealth
  description: Stealth browsing (4)
- name: Tables
  description: Table extraction (2)
- name: LLM
  description: LLM providers (4)
- name: Sessions
  description: Session management (12)
- name: Workers
  description: Job queue (9)
- name: Monitoring
  description: Metrics & alerts (6)
- name: Health
  description: Health checks (2)
paths:
  /healthz:
    get:
      operationId: health_check
      tags:
      - Health
      summary: System health check
      responses:
        '200':
          description: Success
  /metrics:
    get:
      operationId: metrics_prometheus
      tags:
      - Health
      summary: Prometheus metrics
      responses:
        '200':
          description: Success
  /crawl:
    post:
      operationId: crawl_batch
      tags:
      - Crawling
      summary: Batch crawl URLs
      responses:
        '200':
          description: Success
  /crawl/stream:
    post:
      operationId: crawl_stream_ndjson
      tags:
      - Streaming
      summary: Stream crawl results (NDJSON)
      responses:
        '200':
          description: Success
  /crawl/sse:
    post:
      operationId: crawl_stream_sse
      tags:
      - Streaming
      summary: Stream crawl results (SSE)
      responses:
        '200':
          description: Success
  /crawl/ws:
    get:
      operationId: crawl_stream_websocket
      tags:
      - Streaming
      summary: WebSocket crawl stream
      responses:
        '200':
          description: Success
  /deepsearch:
    post:
      tags:
      - Search
      summary: Deep search with extraction
      responses:
        '200':
          description: Success
      operationId: deepsearch_post
  /deepsearch/stream:
    post:
      tags:
      - Streaming
      summary: Stream search results
      responses:
        '200':
          description: Success
      operationId: deepsearch_stream_post
  /render:
    post:
      tags:
      - Crawling
      summary: Headless browser rendering
      responses:
        '200':
          description: Success
      operationId: render_post
  /spider/crawl:
    post:
      tags:
      - Spider
      summary: Deep crawl with Spider
      responses:
        '200':
          description: Success
      operationId: spider_crawl_post
  /spider/status:
    post:
      tags:
      - Spider
      summary: Get spider status
      responses:
        '200':
          description: Success
      operationId: spider_status_post
  /spider/control:
    post:
      tags:
      - Spider
      summary: Control spider (stop/reset)
      responses:
        '200':
          description: Success
      operationId: spider_control_post
  /strategies/crawl:
    post:
      tags:
      - Strategies
      summary: Advanced extraction strategies
      responses:
        '200':
          description: Success
      operationId: strategies_crawl_post
  /strategies/info:
    get:
      tags:
      - Strategies
      summary: Get strategies info
      responses:
        '200':
          description: Success
      operationId: strategies_info_get
  /pdf/process:
    post:
      tags:
      - PDF
      summary: Process PDF file
      responses:
        '200':
          description: Success
      operationId: pdf_process_post
  /pdf/process-stream:
    post:
      tags:
      - PDF
      summary: Stream PDF processing
      responses:
        '200':
          description: Success
      operationId: pdf_process-stream_post
  /pdf/health:
    get:
      tags:
      - PDF
      summary: PDF processor health
      responses:
        '200':
          description: Success
      operationId: pdf_health_get
  /stealth/configure:
    post:
      tags:
      - Stealth
      summary: Configure stealth settings
      responses:
        '200':
          description: Success
      operationId: stealth_configure_post
  /stealth/test:
    post:
      tags:
      - Stealth
      summary: Test stealth effectiveness
      responses:
        '200':
          description: Success
      operationId: stealth_test_post
  /stealth/capabilities:
    get:
      tags:
      - Stealth
      summary: Get stealth capabilities
      responses:
        '200':
          description: Success
      operationId: stealth_capabilities_get
  /stealth/health:
    get:
      tags:
      - Stealth
      summary: Stealth service health
      responses:
        '200':
          description: Success
      operationId: stealth_health_get
  /api/v1/tables/extract:
    post:
      tags:
      - Tables
      summary: Extract tables from HTML
      responses:
        '200':
          description: Success
      operationId: api_v1_tables_extract_post
  /api/v1/tables/{id}/export:
    get:
      tags:
      - Tables
      summary: Export table (CSV/Markdown)
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Table identifier
      responses:
        '200':
          description: Success
      operationId: api_v1_tables_id_export_get
  /api/v1/llm/providers:
    get:
      tags:
      - LLM
      summary: List LLM providers
      responses:
        '200':
          description: Success
      operationId: api_v1_llm_providers_get
  /api/v1/llm/providers/switch:
    post:
      tags:
      - LLM
      summary: Switch LLM provider
      responses:
        '200':
          description: Success
      operationId: api_v1_llm_providers_switch_post
  /api/v1/llm/config:
    get:
      tags:
      - LLM
      summary: Get LLM config
      responses:
        '200':
          description: Success
      operationId: api_v1_llm_config_get
    post:
      tags:
      - LLM
      summary: Update LLM config
      responses:
        '200':
          description: Success
      operationId: api_v1_llm_config_post
  /sessions:
    post:
      tags:
      - Sessions
      summary: Create session
      responses:
        '200':
          description: Success
      operationId: sessions_post
    get:
      tags:
      - Sessions
      summary: List sessions
      responses:
        '200':
          description: Success
      operationId: sessions_get
  /sessions/stats:
    get:
      tags:
      - Sessions
      summary: Session statistics
      responses:
        '200':
          description: Success
      operationId: sessions_stats_get
  /sessions/cleanup:
    post:
      tags:
      - Sessions
      summary: Cleanup expired sessions
      responses:
        '200':
          description: Success
      operationId: sessions_cleanup_post
  /sessions/{session_id}:
    get:
      tags:
      - Sessions
      summary: Get session info
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_get
    delete:
      tags:
      - Sessions
      summary: Delete session
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_delete
  /sessions/{session_id}/extend:
    post:
      tags:
      - Sessions
      summary: Extend session TTL
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_extend_post
  /sessions/{session_id}/cookies:
    post:
      tags:
      - Sessions
      summary: Set cookie
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_cookies_post
    delete:
      tags:
      - Sessions
      summary: Clear all cookies
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_cookies_delete
  /sessions/{session_id}/cookies/{domain}:
    get:
      tags:
      - Sessions
      summary: Get domain cookies
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      - name: domain
        in: path
        required: true
        schema:
          type: string
        description: Cookie domain
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_cookies_domain_get
  /sessions/{session_id}/cookies/{domain}/{name}:
    get:
      tags:
      - Sessions
      summary: Get specific cookie
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      - name: domain
        in: path
        required: true
        schema:
          type: string
        description: Cookie domain
      - name: name
        in: path
        required: true
        schema:
          type: string
        description: Cookie name
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_cookies_domain_name_get
    delete:
      tags:
      - Sessions
      summary: Delete cookie
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
        description: Session identifier
      - name: domain
        in: path
        required: true
        schema:
          type: string
        description: Cookie domain
      - name: name
        in: path
        required: true
        schema:
          type: string
        description: Cookie name
      responses:
        '200':
          description: Success
      operationId: sessions_session_id_cookies_domain_name_delete
  /workers/jobs:
    post:
      tags:
      - Workers
      summary: Submit async job
      responses:
        '200':
          description: Success
      operationId: workers_jobs_post
  /workers/jobs/{job_id}:
    get:
      tags:
      - Workers
      summary: Get job status
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
        description: Job identifier
      responses:
        '200':
          description: Success
      operationId: workers_jobs_job_id_get
  /workers/jobs/{job_id}/result:
    get:
      tags:
      - Workers
      summary: Get job result
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
        description: Job identifier
      responses:
        '200':
          description: Success
      operationId: workers_jobs_job_id_result_get
  /workers/stats/queue:
    get:
      tags:
      - Workers
      summary: Queue statistics
      responses:
        '200':
          description: Success
      operationId: workers_stats_queue_get
  /workers/stats/workers:
    get:
      tags:
      - Workers
      summary: Worker pool stats
      responses:
        '200':
          description: Success
      operationId: workers_stats_workers_get
  /workers/metrics:
    get:
      tags:
      - Workers
      summary: Worker metrics
      responses:
        '200':
          description: Success
      operationId: workers_metrics_get
  /workers/schedule:
    post:
      tags:
      - Workers
      summary: Create scheduled job
      responses:
        '200':
          description: Success
      operationId: workers_schedule_post
    get:
      tags:
      - Workers
      summary: List scheduled jobs
      responses:
        '200':
          description: Success
      operationId: workers_schedule_get
  /workers/schedule/{job_id}:
    delete:
      tags:
      - Workers
      summary: Delete scheduled job
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
        description: Scheduled job identifier
      responses:
        '200':
          description: Success
      operationId: workers_schedule_job_id_delete
  /monitoring/health-score:
    get:
      tags:
      - Monitoring
      summary: System health score (0-100)
      responses:
        '200':
          description: Success
      operationId: monitoring_health-score_get
  /monitoring/performance-report:
    get:
      tags:
      - Monitoring
      summary: Performance report
      responses:
        '200':
          description: Success
      operationId: monitoring_performance-report_get
  /monitoring/metrics/current:
    get:
      tags:
      - Monitoring
      summary: Current metrics snapshot
      responses:
        '200':
          description: Success
      operationId: monitoring_metrics_current_get
  /monitoring/alerts/rules:
    get:
      tags:
      - Monitoring
      summary: Alert rule definitions
      responses:
        '200':
          description: Success
      operationId: monitoring_alerts_rules_get
  /monitoring/alerts/active:
    get:
      tags:
      - Monitoring
      summary: Active alerts
      responses:
        '200':
          description: Success
      operationId: monitoring_alerts_active_get
  /pipeline/phases:
    get:
      tags:
      - Monitoring
      summary: Pipeline phase metrics
      responses:
        '200':
          description: Success
      operationId: pipeline_phases_get
