openapi: 3.0.0
info:
  title: RipTide API - Comprehensive Specification
  version: 1.0.0
  description: '# RipTide Crawler API


    A high-performance web scraping and content extraction API with 59 endpoints across 12 categories.


    ## Phase 1: Core Crawling & Event System (11 endpoints)

    - `/crawl` - Batch URL crawling with adaptive gate system

    - `/crawl/stream`, `/crawl/sse`, `/crawl/ws` - Real-time streaming

    - `/deepsearch`, `/deepsearch/stream` - Web search integration

    - `/render` - Headless browser rendering

    - `/healthz`, `/metrics` - System health and Prometheus metrics


    ## Phase 2: Advanced Extraction (14 endpoints)

    - `/strategies/*` - Multi-strategy extraction (CSS, TREK, LLM, Regex)

    - `/pdf/*` - PDF processing with progress streaming

    - `/api/v1/tables/*` - Table extraction and export (CSV/Markdown)


    ## Phase 3: Enterprise Features (34 endpoints)

    - `/spider/*` - Deep crawling with frontier management (3)

    - `/stealth/*` - Stealth configuration and testing (4)

    - `/api/v1/llm/*` - LLM provider management (4)

    - `/sessions/*` - Session and cookie management (12)

    - `/workers/*` - Async job queue and scheduling (9)

    - `/monitoring/*` - Health monitoring and alerts (6)


    ## Architecture Highlights

    - **Dual-Path Pipeline**: Fast CSS + async AI enhancement

    - **Event-Driven**: Core event bus for monitoring

    - **Circuit Breaker**: Automatic failover for dependencies

    - **Adaptive Gate**: Smart routing (raw/probes/headless/cached)


    **Total: 59 endpoints documented**

    '
  contact:
    name: RipTide API Support
    url: https://github.com/riptide/api
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: http://localhost:8080
  description: Local development
- url: https://api.riptide.example.com
  description: Production
tags:
- name: Crawling
  description: Core crawling endpoints (5)
- name: Search
  description: Deep search endpoints (2)
- name: Spider
  description: Deep crawling (3)
- name: Streaming
  description: Real-time streaming (4)
- name: Strategies
  description: Advanced extraction (2)
- name: PDF
  description: PDF processing (3)
- name: Stealth
  description: Stealth browsing (4)
- name: Tables
  description: Table extraction (2)
- name: LLM
  description: LLM providers (4)
- name: Sessions
  description: Session management (12)
- name: Workers
  description: Job queue (9)
- name: Monitoring
  description: Metrics & alerts (6)
- name: Health
  description: Health checks (2)
paths:
  /healthz:
    get:
      tags:
      - Health
      summary: System health check
  /metrics:
    get:
      tags:
      - Health
      summary: Prometheus metrics
  /crawl:
    post:
      tags:
      - Crawling
      summary: Batch crawl URLs
  /crawl/stream:
    post:
      tags:
      - Streaming
      summary: Stream crawl results (NDJSON)
  /crawl/sse:
    post:
      tags:
      - Streaming
      summary: Stream crawl results (SSE)
  /crawl/ws:
    get:
      tags:
      - Streaming
      summary: WebSocket crawl stream
  /deepsearch:
    post:
      tags:
      - Search
      summary: Deep search with extraction
  /deepsearch/stream:
    post:
      tags:
      - Streaming
      summary: Stream search results
  /render:
    post:
      tags:
      - Crawling
      summary: Headless browser rendering
  /spider/crawl:
    post:
      tags:
      - Spider
      summary: Deep crawl with Spider
  /spider/status:
    post:
      tags:
      - Spider
      summary: Get spider status
  /spider/control:
    post:
      tags:
      - Spider
      summary: Control spider (stop/reset)
  /strategies/crawl:
    post:
      tags:
      - Strategies
      summary: Advanced extraction strategies
  /strategies/info:
    get:
      tags:
      - Strategies
      summary: Get strategies info
  /pdf/process:
    post:
      tags:
      - PDF
      summary: Process PDF file
  /pdf/process-stream:
    post:
      tags:
      - PDF
      summary: Stream PDF processing
  /pdf/health:
    get:
      tags:
      - PDF
      summary: PDF processor health
  /stealth/configure:
    post:
      tags:
      - Stealth
      summary: Configure stealth settings
  /stealth/test:
    post:
      tags:
      - Stealth
      summary: Test stealth effectiveness
  /stealth/capabilities:
    get:
      tags:
      - Stealth
      summary: Get stealth capabilities
  /stealth/health:
    get:
      tags:
      - Stealth
      summary: Stealth service health
  /api/v1/tables/extract:
    post:
      tags:
      - Tables
      summary: Extract tables from HTML
  /api/v1/tables/{id}/export:
    get:
      tags:
      - Tables
      summary: Export table (CSV/Markdown)
  /api/v1/llm/providers:
    get:
      tags:
      - LLM
      summary: List LLM providers
  /api/v1/llm/providers/switch:
    post:
      tags:
      - LLM
      summary: Switch LLM provider
  /api/v1/llm/config:
    get:
      tags:
      - LLM
      summary: Get LLM config
    post:
      tags:
      - LLM
      summary: Update LLM config
  /sessions:
    post:
      tags:
      - Sessions
      summary: Create session
    get:
      tags:
      - Sessions
      summary: List sessions
  /sessions/stats:
    get:
      tags:
      - Sessions
      summary: Session statistics
  /sessions/cleanup:
    post:
      tags:
      - Sessions
      summary: Cleanup expired sessions
  /sessions/{session_id}:
    get:
      tags:
      - Sessions
      summary: Get session info
    delete:
      tags:
      - Sessions
      summary: Delete session
  /sessions/{session_id}/extend:
    post:
      tags:
      - Sessions
      summary: Extend session TTL
  /sessions/{session_id}/cookies:
    post:
      tags:
      - Sessions
      summary: Set cookie
    delete:
      tags:
      - Sessions
      summary: Clear all cookies
  /sessions/{session_id}/cookies/{domain}:
    get:
      tags:
      - Sessions
      summary: Get domain cookies
  /sessions/{session_id}/cookies/{domain}/{name}:
    get:
      tags:
      - Sessions
      summary: Get specific cookie
    delete:
      tags:
      - Sessions
      summary: Delete cookie
  /workers/jobs:
    post:
      tags:
      - Workers
      summary: Submit async job
  /workers/jobs/{job_id}:
    get:
      tags:
      - Workers
      summary: Get job status
  /workers/jobs/{job_id}/result:
    get:
      tags:
      - Workers
      summary: Get job result
  /workers/stats/queue:
    get:
      tags:
      - Workers
      summary: Queue statistics
  /workers/stats/workers:
    get:
      tags:
      - Workers
      summary: Worker pool stats
  /workers/metrics:
    get:
      tags:
      - Workers
      summary: Worker metrics
  /workers/schedule:
    post:
      tags:
      - Workers
      summary: Create scheduled job
    get:
      tags:
      - Workers
      summary: List scheduled jobs
  /workers/schedule/{job_id}:
    delete:
      tags:
      - Workers
      summary: Delete scheduled job
  /monitoring/health-score:
    get:
      tags:
      - Monitoring
      summary: System health score (0-100)
  /monitoring/performance-report:
    get:
      tags:
      - Monitoring
      summary: Performance report
  /monitoring/metrics/current:
    get:
      tags:
      - Monitoring
      summary: Current metrics snapshot
  /monitoring/alerts/rules:
    get:
      tags:
      - Monitoring
      summary: Alert rule definitions
  /monitoring/alerts/active:
    get:
      tags:
      - Monitoring
      summary: Active alerts
  /pipeline/phases:
    get:
      tags:
      - Monitoring
      summary: Pipeline phase metrics
